<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Blix.Cooked\Blix.Cooked.csproj" />
    <ProjectReference Include="..\Blix.Geometry\Blix.Geometry.csproj" />
    <ProjectReference Include="..\Blix.Graphics\Blix.Graphics.csproj" />
    <ProjectReference Include="..\Blix.Graphics.Images\Blix.Graphics.Images.csproj" />
    <ProjectReference Include="..\Blix.Audio\Blix.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StbTrueTypeSharp" Version="1.26.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
