#pragma once

// Sheen and diffuse transmission -- the two responses cloth needs that the
// metallic-roughness lobe cannot give it.
//
// Vocabulary, not a turn-key evaluator, for the same reason pbr.glsl is: the
// surrounding light state varies too much between consumers for one-shot
// evaluation to land. What is fixed here is the SPEC's answer, so that the
// engine's default and the studio's default are one file rather than two that
// drift. A consumer wanting something cheaper writes it at its own call site.
//
// Both terms come from glTF: KHR_materials_sheen and
// KHR_materials_diffuse_transmission. They are separate extensions because they
// are separate physics -- one is a rim you see, the other is light you see
// through -- and a curtain wants both.

#ifndef BLIX_PI
#define BLIX_PI 3.14159265359
#endif

// --- Sheen distribution (D) -----------------------------------------------
// The "Charlie" distribution (Estevez & Kulla 2017), which is what the glTF
// spec names. GGX is the wrong shape for fabric: a microfacet model assumes
// facets distributed about the surface normal, and cloth is fibres standing
// AWAY from it. The visible consequence is the bright rim on velvet at grazing
// angles, where GGX gives almost nothing -- and it is exactly the cue that
// makes a curtain read as cloth rather than as a painted board.
//
// sin^(1/a) rather than an exponential: the inverted roughness puts the lobe's
// energy at the horizon instead of at the normal.
float blix_sheenDistributionCharlie(float NdotH, float sheenRoughness)
{
    float alpha = max(sheenRoughness * sheenRoughness, 1e-4);
    float invAlpha = 1.0 / alpha;
    float cos2h = NdotH * NdotH;
    float sin2h = max(1.0 - cos2h, 1e-7);
    return (2.0 + invAlpha) * pow(sin2h, invAlpha * 0.5) / (2.0 * BLIX_PI);
}

// --- Sheen visibility (V) -------------------------------------------------
// Ashikhmin's, as the spec specifies. Note this is the VISIBILITY term -- the
// geometry term with the 4*NdotL*NdotV denominator already folded in -- so a
// consumer multiplies D * V * F and does NOT divide again. Getting that wrong
// is a factor of 4*NdotL*NdotV, which reads as "sheen is too strong at grazing
// angles", which is precisely where sheen is supposed to be strong. It looks
// plausible and it is wrong.
float blix_sheenVisibilityAshikhmin(float NdotL, float NdotV)
{
    return clamp(1.0 / (4.0 * (NdotL + NdotV - NdotL * NdotV)), 0.0, 1.0);
}

// --- The sheen lobe -------------------------------------------------------
// sheenColor is the material's KHR_materials_sheen colour factor; it takes the
// place of a Fresnel term, which fabric does not have in the dielectric sense.
vec3 blix_sheenBrdf(vec3 sheenColor, float sheenRoughness, float NdotH, float NdotL, float NdotV)
{
    float d = blix_sheenDistributionCharlie(NdotH, sheenRoughness);
    float v = blix_sheenVisibilityAshikhmin(NdotL, NdotV);
    return sheenColor * d * v;
}

// --- Energy compensation --------------------------------------------------
// How much light the sheen layer takes, so the base layer beneath it can be
// darkened by that much. WITHOUT this, sheen is added energy and a curtain gets
// brighter than the light falling on it -- the failure that makes a sheen
// implementation look like a bloom bug.
//
// The quantity is the Charlie lobe's DIRECTIONAL ALBEDO, E(NdotV, roughness):
// the integral of D*V*NdotL over the hemisphere. It has no closed form, so the
// glTF spec ships it as a lookup table, and so do we -- generated by the same
// cook that already bakes the split-sum BRDF LUT beside it.
//
// <b>An analytic fit stood here first and was wrong.</b> Published approximations
// to this integral exist; the one written here from memory disagreed with the
// numerically integrated lobe by two orders of magnitude at low roughness --
// 0.4694 against 0.0001 at roughness 0.1, NdotV 0.6 -- in the direction that
// would have darkened cloth that should be untouched. It survived a compile, a
// range check and a clamp, because a fit that returns plausible numbers in [0,1]
// looks correct from everywhere except the integral it claims to approximate.
// A table computed by the cook cannot be wrong in that particular way.
//
// u = NdotV, v = sheenRoughness. R channel.
float blix_sheenAlbedo(sampler2D sheenLut, float NdotV, float sheenRoughness)
{
    return texture(sheenLut, vec2(clamp(NdotV, 0.0, 1.0), clamp(sheenRoughness, 0.0, 1.0))).r;
}

// The factor the base (diffuse + specular) layer is multiplied by, so the pair
// conserves energy. max over the channels because the sheen layer occludes
// geometrically, not per wavelength: a red sheen still shadows the blue beneath.
float blix_sheenScaling(vec3 sheenColor, float sheenAlbedo)
{
    return 1.0 - max(max(sheenColor.r, sheenColor.g), sheenColor.b) * sheenAlbedo;
}

// --- Diffuse transmission -------------------------------------------------
// KHR_materials_diffuse_transmission: light that enters the back of a thin
// surface and scatters out the front. This is what a leaf and a single layer of
// cloth do, and it is NOT KHR_materials_transmission -- that one is a clear
// pane you see THROUGH, refracting; this one is a sheet that GLOWS when the sun
// is behind it, carrying no image at all.
//
// Lambertian about the INVERTED normal, which is the whole trick: the same
// diffuse response, asked about the side the light is actually on. A consumer
// passes the light it already computed for the front and gets the back for the
// cost of one dot product.
vec3 blix_diffuseTransmission(
    vec3 N, vec3 L, vec3 radiance, vec3 transmissionColor, float transmissionFactor)
{
    float backNdotL = max(dot(-N, L), 0.0);
    return radiance * backNdotL * transmissionColor * transmissionFactor / BLIX_PI;
}

// The ambient half: irradiance gathered along -N rather than N. The consumer
// supplies the value from its own irradiance cube, because which cube that is,
// and whether it is bent-normal corrected, is the consumer's decision.
vec3 blix_diffuseTransmissionAmbient(
    vec3 backIrradiance, vec3 transmissionColor, float transmissionFactor)
{
    return backIrradiance * transmissionColor * transmissionFactor;
}

// What the OPAQUE base layer keeps once the transmitted part is accounted for.
// Energy that went out the back did not come out the front, and a consumer that
// adds transmission without this makes cloth a light source.
float blix_diffuseTransmissionScaling(float transmissionFactor)
{
    return 1.0 - clamp(transmissionFactor, 0.0, 1.0);
}
