<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Blix.Core\Blix.Core.csproj" />
    <ProjectReference Include="..\Blix.Geometry\Blix.Geometry.csproj" />
    <ProjectReference Include="..\Blix.Graphics\Blix.Graphics.csproj" />
    <ProjectReference Include="..\Blix.Render\Blix.Render.csproj" />
    <ProjectReference Include="..\Blix.Audio\Blix.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
